//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.30 at 11:18:11 PM EST 
//


package com.glenwood.glaceemr.infobutton.utils.KnowledgeRequest;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.glenwood.glaceemr.infobutton.utils.KnowledgeRequest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MainSearchCriteria_QNAME = new QName("urn:hl7-org:v3", "mainSearchCriteria");
    private final static QName _Encounter_QNAME = new QName("urn:hl7-org:v3", "encounter");
    private final static QName _InformationRecipient_QNAME = new QName("urn:hl7-org:v3", "informationRecipient");
    private final static QName _SubTopic_QNAME = new QName("urn:hl7-org:v3", "subTopic");
    private final static QName _Performer_QNAME = new QName("urn:hl7-org:v3", "performer");
    private final static QName _REDSMT010001UVKnowledgeRequestNotification_QNAME = new QName("urn:hl7-org:v3", "REDS_MT010001UV.KnowledgeRequestNotification");
    private final static QName _TaskContext_QNAME = new QName("urn:hl7-org:v3", "taskContext");
    private final static QName _PatientContext_QNAME = new QName("urn:hl7-org:v3", "patientContext");
    private final static QName _REDSMT010001UVSubject6AgeGroup_QNAME = new QName("urn:hl7-org:v3", "ageGroup");
    private final static QName _REDSMT010001UVSubject6Age_QNAME = new QName("urn:hl7-org:v3", "age");
    private final static QName _REDSMT010001UVEncounterLocation_QNAME = new QName("urn:hl7-org:v3", "location");
    private final static QName _ENSuffix_QNAME = new QName("urn:hl7-org:v3", "suffix");
    private final static QName _ENDelimiter_QNAME = new QName("urn:hl7-org:v3", "delimiter");
    private final static QName _ENValidTime_QNAME = new QName("urn:hl7-org:v3", "validTime");
    private final static QName _ENPrefix_QNAME = new QName("urn:hl7-org:v3", "prefix");
    private final static QName _ENFamily_QNAME = new QName("urn:hl7-org:v3", "family");
    private final static QName _ENGiven_QNAME = new QName("urn:hl7-org:v3", "given");
    private final static QName _IVLTSHigh_QNAME = new QName("urn:hl7-org:v3", "high");
    private final static QName _IVLTSLow_QNAME = new QName("urn:hl7-org:v3", "low");
    private final static QName _IVLTSCenter_QNAME = new QName("urn:hl7-org:v3", "center");
    private final static QName _IVLTSWidth_QNAME = new QName("urn:hl7-org:v3", "width");
    private final static QName _REDSMT010001UVInformationRecipientPatient_QNAME = new QName("urn:hl7-org:v3", "patient");
    private final static QName _REDSMT010001UVInformationRecipientHealthCareProvider_QNAME = new QName("urn:hl7-org:v3", "healthCareProvider");
    private final static QName _REDSMT010001UVHealthCareProviderHealthCarePerson_QNAME = new QName("urn:hl7-org:v3", "healthCarePerson");
    private final static QName _REDSMT010001UVAssignedEntityRepresentedOrganization_QNAME = new QName("urn:hl7-org:v3", "representedOrganization");
    private final static QName _REDSMT010001UVAssignedEntityAssignedAuthorizedPerson_QNAME = new QName("urn:hl7-org:v3", "assignedAuthorizedPerson");
    private final static QName _REDSMT010001UVPatientPatientPerson_QNAME = new QName("urn:hl7-org:v3", "patientPerson");
    private final static QName _REDSMT010001UVKnowledgeRequestNotificationSubject1_QNAME = new QName("urn:hl7-org:v3", "subject1");
    private final static QName _REDSMT010001UVKnowledgeRequestNotificationHolder_QNAME = new QName("urn:hl7-org:v3", "holder");
    private final static QName _REDSMT010001UVKnowledgeRequestNotificationSubject3_QNAME = new QName("urn:hl7-org:v3", "subject3");
    private final static QName _REDSMT010001UVKnowledgeRequestNotificationSubject2_QNAME = new QName("urn:hl7-org:v3", "subject2");
    private final static QName _REDSMT010001UVKnowledgeRequestNotificationComponentOf_QNAME = new QName("urn:hl7-org:v3", "componentOf");
    private final static QName _ADDeliveryModeIdentifier_QNAME = new QName("urn:hl7-org:v3", "deliveryModeIdentifier");
    private final static QName _ADHouseNumber_QNAME = new QName("urn:hl7-org:v3", "houseNumber");
    private final static QName _ADState_QNAME = new QName("urn:hl7-org:v3", "state");
    private final static QName _ADCity_QNAME = new QName("urn:hl7-org:v3", "city");
    private final static QName _ADAdditionalLocator_QNAME = new QName("urn:hl7-org:v3", "additionalLocator");
    private final static QName _ADStreetAddressLine_QNAME = new QName("urn:hl7-org:v3", "streetAddressLine");
    private final static QName _ADDeliveryInstallationArea_QNAME = new QName("urn:hl7-org:v3", "deliveryInstallationArea");
    private final static QName _ADStreetNameType_QNAME = new QName("urn:hl7-org:v3", "streetNameType");
    private final static QName _ADDeliveryInstallationQualifier_QNAME = new QName("urn:hl7-org:v3", "deliveryInstallationQualifier");
    private final static QName _ADDirection_QNAME = new QName("urn:hl7-org:v3", "direction");
    private final static QName _ADCensusTract_QNAME = new QName("urn:hl7-org:v3", "censusTract");
    private final static QName _ADUnitID_QNAME = new QName("urn:hl7-org:v3", "unitID");
    private final static QName _ADPostalCode_QNAME = new QName("urn:hl7-org:v3", "postalCode");
    private final static QName _ADStreetName_QNAME = new QName("urn:hl7-org:v3", "streetName");
    private final static QName _ADDeliveryInstallationType_QNAME = new QName("urn:hl7-org:v3", "deliveryInstallationType");
    private final static QName _ADStreetNameBase_QNAME = new QName("urn:hl7-org:v3", "streetNameBase");
    private final static QName _ADDeliveryMode_QNAME = new QName("urn:hl7-org:v3", "deliveryMode");
    private final static QName _ADPostBox_QNAME = new QName("urn:hl7-org:v3", "postBox");
    private final static QName _ADCountry_QNAME = new QName("urn:hl7-org:v3", "country");
    private final static QName _ADDeliveryAddressLine_QNAME = new QName("urn:hl7-org:v3", "deliveryAddressLine");
    private final static QName _ADUseablePeriod_QNAME = new QName("urn:hl7-org:v3", "useablePeriod");
    private final static QName _ADCareOf_QNAME = new QName("urn:hl7-org:v3", "careOf");
    private final static QName _ADUnitType_QNAME = new QName("urn:hl7-org:v3", "unitType");
    private final static QName _ADPrecinct_QNAME = new QName("urn:hl7-org:v3", "precinct");
    private final static QName _ADBuildingNumberSuffix_QNAME = new QName("urn:hl7-org:v3", "buildingNumberSuffix");
    private final static QName _ADHouseNumberNumeric_QNAME = new QName("urn:hl7-org:v3", "houseNumberNumeric");
    private final static QName _ADCounty_QNAME = new QName("urn:hl7-org:v3", "county");
    private final static QName _REDSMT010001UVMainSearchCriteriaSubject_QNAME = new QName("urn:hl7-org:v3", "subject");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.glenwood.glaceemr.infobutton.utils.KnowledgeRequest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link REDSMT010001UVPatientContext }
     * 
     */
    public REDSMT010001UVPatientContext createREDSMT010001UVPatientContext() {
        return new REDSMT010001UVPatientContext();
    }

    /**
     * Create an instance of {@link REDSMT010001UVTaskContext }
     * 
     */
    public REDSMT010001UVTaskContext createREDSMT010001UVTaskContext() {
        return new REDSMT010001UVTaskContext();
    }

    /**
     * Create an instance of {@link REDSMT010001UVKnowledgeRequestNotification }
     * 
     */
    public REDSMT010001UVKnowledgeRequestNotification createREDSMT010001UVKnowledgeRequestNotification() {
        return new REDSMT010001UVKnowledgeRequestNotification();
    }

    /**
     * Create an instance of {@link REDSMT010001UVPerformer }
     * 
     */
    public REDSMT010001UVPerformer createREDSMT010001UVPerformer() {
        return new REDSMT010001UVPerformer();
    }

    /**
     * Create an instance of {@link REDSMT010001UVSubTopic }
     * 
     */
    public REDSMT010001UVSubTopic createREDSMT010001UVSubTopic() {
        return new REDSMT010001UVSubTopic();
    }

    /**
     * Create an instance of {@link REDSMT010001UVInformationRecipient }
     * 
     */
    public REDSMT010001UVInformationRecipient createREDSMT010001UVInformationRecipient() {
        return new REDSMT010001UVInformationRecipient();
    }

    /**
     * Create an instance of {@link REDSMT010001UVEncounter }
     * 
     */
    public REDSMT010001UVEncounter createREDSMT010001UVEncounter() {
        return new REDSMT010001UVEncounter();
    }

    /**
     * Create an instance of {@link REDSMT010001UVMainSearchCriteria }
     * 
     */
    public REDSMT010001UVMainSearchCriteria createREDSMT010001UVMainSearchCriteria() {
        return new REDSMT010001UVMainSearchCriteria();
    }

    /**
     * Create an instance of {@link BXITIVLPQ }
     * 
     */
    public BXITIVLPQ createBXITIVLPQ() {
        return new BXITIVLPQ();
    }

    /**
     * Create an instance of {@link REDSMT010001UVPerson }
     * 
     */
    public REDSMT010001UVPerson createREDSMT010001UVPerson() {
        return new REDSMT010001UVPerson();
    }

    /**
     * Create an instance of {@link ED }
     * 
     */
    public ED createED() {
        return new ED();
    }

    /**
     * Create an instance of {@link EN }
     * 
     */
    public EN createEN() {
        return new EN();
    }

    /**
     * Create an instance of {@link SXCMPQ }
     * 
     */
    public SXCMPQ createSXCMPQ() {
        return new SXCMPQ();
    }

    /**
     * Create an instance of {@link REDSMT010001UVAuthorizedPerson }
     * 
     */
    public REDSMT010001UVAuthorizedPerson createREDSMT010001UVAuthorizedPerson() {
        return new REDSMT010001UVAuthorizedPerson();
    }

    /**
     * Create an instance of {@link AdxpDeliveryInstallationType }
     * 
     */
    public AdxpDeliveryInstallationType createAdxpDeliveryInstallationType() {
        return new AdxpDeliveryInstallationType();
    }

    /**
     * Create an instance of {@link EIVLTS }
     * 
     */
    public EIVLTS createEIVLTS() {
        return new EIVLTS();
    }

    /**
     * Create an instance of {@link INT }
     * 
     */
    public INT createINT() {
        return new INT();
    }

    /**
     * Create an instance of {@link AdxpPrecinct }
     * 
     */
    public AdxpPrecinct createAdxpPrecinct() {
        return new AdxpPrecinct();
    }

    /**
     * Create an instance of {@link AD }
     * 
     */
    public AD createAD() {
        return new AD();
    }

    /**
     * Create an instance of {@link SXCMMO }
     * 
     */
    public SXCMMO createSXCMMO() {
        return new SXCMMO();
    }

    /**
     * Create an instance of {@link BN }
     * 
     */
    public BN createBN() {
        return new BN();
    }

    /**
     * Create an instance of {@link BL }
     * 
     */
    public BL createBL() {
        return new BL();
    }

    /**
     * Create an instance of {@link CV }
     * 
     */
    public CV createCV() {
        return new CV();
    }

    /**
     * Create an instance of {@link EnDelimiter }
     * 
     */
    public EnDelimiter createEnDelimiter() {
        return new EnDelimiter();
    }

    /**
     * Create an instance of {@link CS }
     * 
     */
    public CS createCS() {
        return new CS();
    }

    /**
     * Create an instance of {@link SLISTPQ }
     * 
     */
    public SLISTPQ createSLISTPQ() {
        return new SLISTPQ();
    }

    /**
     * Create an instance of {@link CE }
     * 
     */
    public CE createCE() {
        return new CE();
    }

    /**
     * Create an instance of {@link CD }
     * 
     */
    public CD createCD() {
        return new CD();
    }

    /**
     * Create an instance of {@link CR }
     * 
     */
    public CR createCR() {
        return new CR();
    }

    /**
     * Create an instance of {@link CO }
     * 
     */
    public CO createCO() {
        return new CO();
    }

    /**
     * Create an instance of {@link IVLPPDTS }
     * 
     */
    public IVLPPDTS createIVLPPDTS() {
        return new IVLPPDTS();
    }

    /**
     * Create an instance of {@link IVXBREAL }
     * 
     */
    public IVXBREAL createIVXBREAL() {
        return new IVXBREAL();
    }

    /**
     * Create an instance of {@link AdxpUnitID }
     * 
     */
    public AdxpUnitID createAdxpUnitID() {
        return new AdxpUnitID();
    }

    /**
     * Create an instance of {@link MO }
     * 
     */
    public MO createMO() {
        return new MO();
    }

    /**
     * Create an instance of {@link ON }
     * 
     */
    public ON createON() {
        return new ON();
    }

    /**
     * Create an instance of {@link RTOPQPQ }
     * 
     */
    public RTOPQPQ createRTOPQPQ() {
        return new RTOPQPQ();
    }

    /**
     * Create an instance of {@link PN }
     * 
     */
    public PN createPN() {
        return new PN();
    }

    /**
     * Create an instance of {@link EnSuffix }
     * 
     */
    public EnSuffix createEnSuffix() {
        return new EnSuffix();
    }

    /**
     * Create an instance of {@link AdxpDeliveryInstallationQualifier }
     * 
     */
    public AdxpDeliveryInstallationQualifier createAdxpDeliveryInstallationQualifier() {
        return new AdxpDeliveryInstallationQualifier();
    }

    /**
     * Create an instance of {@link IVLPPDPQ }
     * 
     */
    public IVLPPDPQ createIVLPPDPQ() {
        return new IVLPPDPQ();
    }

    /**
     * Create an instance of {@link HXITPQ }
     * 
     */
    public HXITPQ createHXITPQ() {
        return new HXITPQ();
    }

    /**
     * Create an instance of {@link EIVLPPDTS }
     * 
     */
    public EIVLPPDTS createEIVLPPDTS() {
        return new EIVLPPDTS();
    }

    /**
     * Create an instance of {@link II }
     * 
     */
    public II createII() {
        return new II();
    }

    /**
     * Create an instance of {@link SXCMTS }
     * 
     */
    public SXCMTS createSXCMTS() {
        return new SXCMTS();
    }

    /**
     * Create an instance of {@link AdxpBuildingNumberSuffix }
     * 
     */
    public AdxpBuildingNumberSuffix createAdxpBuildingNumberSuffix() {
        return new AdxpBuildingNumberSuffix();
    }

    /**
     * Create an instance of {@link REDSMT010001UVHealthCareProvider }
     * 
     */
    public REDSMT010001UVHealthCareProvider createREDSMT010001UVHealthCareProvider() {
        return new REDSMT010001UVHealthCareProvider();
    }

    /**
     * Create an instance of {@link IVXBPPDTS }
     * 
     */
    public IVXBPPDTS createIVXBPPDTS() {
        return new IVXBPPDTS();
    }

    /**
     * Create an instance of {@link IVLTS }
     * 
     */
    public IVLTS createIVLTS() {
        return new IVLTS();
    }

    /**
     * Create an instance of {@link SXPRTS }
     * 
     */
    public SXPRTS createSXPRTS() {
        return new SXPRTS();
    }

    /**
     * Create an instance of {@link REDSMT010001UVPatientPerson }
     * 
     */
    public REDSMT010001UVPatientPerson createREDSMT010001UVPatientPerson() {
        return new REDSMT010001UVPatientPerson();
    }

    /**
     * Create an instance of {@link IVLPQ }
     * 
     */
    public IVLPQ createIVLPQ() {
        return new IVLPQ();
    }

    /**
     * Create an instance of {@link AdxpCensusTract }
     * 
     */
    public AdxpCensusTract createAdxpCensusTract() {
        return new AdxpCensusTract();
    }

    /**
     * Create an instance of {@link REAL }
     * 
     */
    public REAL createREAL() {
        return new REAL();
    }

    /**
     * Create an instance of {@link PIVLPPDTS }
     * 
     */
    public PIVLPPDTS createPIVLPPDTS() {
        return new PIVLPPDTS();
    }

    /**
     * Create an instance of {@link IVLREAL }
     * 
     */
    public IVLREAL createIVLREAL() {
        return new IVLREAL();
    }

    /**
     * Create an instance of {@link SXCMPPDTS }
     * 
     */
    public SXCMPPDTS createSXCMPPDTS() {
        return new SXCMPPDTS();
    }

    /**
     * Create an instance of {@link IVXBPPDPQ }
     * 
     */
    public IVXBPPDPQ createIVXBPPDPQ() {
        return new IVXBPPDPQ();
    }

    /**
     * Create an instance of {@link AdxpDeliveryAddressLine }
     * 
     */
    public AdxpDeliveryAddressLine createAdxpDeliveryAddressLine() {
        return new AdxpDeliveryAddressLine();
    }

    /**
     * Create an instance of {@link PQ }
     * 
     */
    public PQ createPQ() {
        return new PQ();
    }

    /**
     * Create an instance of {@link REDSMT010001UVComponent1 }
     * 
     */
    public REDSMT010001UVComponent1 createREDSMT010001UVComponent1() {
        return new REDSMT010001UVComponent1();
    }

    /**
     * Create an instance of {@link TN }
     * 
     */
    public TN createTN() {
        return new TN();
    }

    /**
     * Create an instance of {@link TS }
     * 
     */
    public TS createTS() {
        return new TS();
    }

    /**
     * Create an instance of {@link ST }
     * 
     */
    public ST createST() {
        return new ST();
    }

    /**
     * Create an instance of {@link SC }
     * 
     */
    public SC createSC() {
        return new SC();
    }

    /**
     * Create an instance of {@link IVLMO }
     * 
     */
    public IVLMO createIVLMO() {
        return new IVLMO();
    }

    /**
     * Create an instance of {@link REDSMT010001UVHolder }
     * 
     */
    public REDSMT010001UVHolder createREDSMT010001UVHolder() {
        return new REDSMT010001UVHolder();
    }

    /**
     * Create an instance of {@link AdxpState }
     * 
     */
    public AdxpState createAdxpState() {
        return new AdxpState();
    }

    /**
     * Create an instance of {@link AdxpCity }
     * 
     */
    public AdxpCity createAdxpCity() {
        return new AdxpCity();
    }

    /**
     * Create an instance of {@link RTOMOPQ }
     * 
     */
    public RTOMOPQ createRTOMOPQ() {
        return new RTOMOPQ();
    }

    /**
     * Create an instance of {@link SXCMPPDPQ }
     * 
     */
    public SXCMPPDPQ createSXCMPPDPQ() {
        return new SXCMPPDPQ();
    }

    /**
     * Create an instance of {@link RTOQTYQTY }
     * 
     */
    public RTOQTYQTY createRTOQTYQTY() {
        return new RTOQTYQTY();
    }

    /**
     * Create an instance of {@link SLISTTS }
     * 
     */
    public SLISTTS createSLISTTS() {
        return new SLISTTS();
    }

    /**
     * Create an instance of {@link BXITCD }
     * 
     */
    public BXITCD createBXITCD() {
        return new BXITCD();
    }

    /**
     * Create an instance of {@link REDSMT010001UVLanguageCommunication }
     * 
     */
    public REDSMT010001UVLanguageCommunication createREDSMT010001UVLanguageCommunication() {
        return new REDSMT010001UVLanguageCommunication();
    }

    /**
     * Create an instance of {@link SXCMCD }
     * 
     */
    public SXCMCD createSXCMCD() {
        return new SXCMCD();
    }

    /**
     * Create an instance of {@link SXCMINT }
     * 
     */
    public SXCMINT createSXCMINT() {
        return new SXCMINT();
    }

    /**
     * Create an instance of {@link HXITCE }
     * 
     */
    public HXITCE createHXITCE() {
        return new HXITCE();
    }

    /**
     * Create an instance of {@link AdxpPostBox }
     * 
     */
    public AdxpPostBox createAdxpPostBox() {
        return new AdxpPostBox();
    }

    /**
     * Create an instance of {@link ADXP }
     * 
     */
    public ADXP createADXP() {
        return new ADXP();
    }

    /**
     * Create an instance of {@link AdxpDeliveryInstallationArea }
     * 
     */
    public AdxpDeliveryInstallationArea createAdxpDeliveryInstallationArea() {
        return new AdxpDeliveryInstallationArea();
    }

    /**
     * Create an instance of {@link AdxpDeliveryMode }
     * 
     */
    public AdxpDeliveryMode createAdxpDeliveryMode() {
        return new AdxpDeliveryMode();
    }

    /**
     * Create an instance of {@link ANYNonNull }
     * 
     */
    public ANYNonNull createANYNonNull() {
        return new ANYNonNull();
    }

    /**
     * Create an instance of {@link AdxpDelimiter }
     * 
     */
    public AdxpDelimiter createAdxpDelimiter() {
        return new AdxpDelimiter();
    }

    /**
     * Create an instance of {@link UVPTS }
     * 
     */
    public UVPTS createUVPTS() {
        return new UVPTS();
    }

    /**
     * Create an instance of {@link AdxpStreetAddressLine }
     * 
     */
    public AdxpStreetAddressLine createAdxpStreetAddressLine() {
        return new AdxpStreetAddressLine();
    }

    /**
     * Create an instance of {@link AdxpUnitType }
     * 
     */
    public AdxpUnitType createAdxpUnitType() {
        return new AdxpUnitType();
    }

    /**
     * Create an instance of {@link AdxpCountry }
     * 
     */
    public AdxpCountry createAdxpCountry() {
        return new AdxpCountry();
    }

    /**
     * Create an instance of {@link AdxpHouseNumberNumeric }
     * 
     */
    public AdxpHouseNumberNumeric createAdxpHouseNumberNumeric() {
        return new AdxpHouseNumberNumeric();
    }

    /**
     * Create an instance of {@link AdxpCareOf }
     * 
     */
    public AdxpCareOf createAdxpCareOf() {
        return new AdxpCareOf();
    }

    /**
     * Create an instance of {@link EnPrefix }
     * 
     */
    public EnPrefix createEnPrefix() {
        return new EnPrefix();
    }

    /**
     * Create an instance of {@link IVXBTS }
     * 
     */
    public IVXBTS createIVXBTS() {
        return new IVXBTS();
    }

    /**
     * Create an instance of {@link REDSMT010001UVPatient }
     * 
     */
    public REDSMT010001UVPatient createREDSMT010001UVPatient() {
        return new REDSMT010001UVPatient();
    }

    /**
     * Create an instance of {@link PPDPQ }
     * 
     */
    public PPDPQ createPPDPQ() {
        return new PPDPQ();
    }

    /**
     * Create an instance of {@link TEL }
     * 
     */
    public TEL createTEL() {
        return new TEL();
    }

    /**
     * Create an instance of {@link REDSMT010001UVAge }
     * 
     */
    public REDSMT010001UVAge createREDSMT010001UVAge() {
        return new REDSMT010001UVAge();
    }

    /**
     * Create an instance of {@link AdxpCounty }
     * 
     */
    public AdxpCounty createAdxpCounty() {
        return new AdxpCounty();
    }

    /**
     * Create an instance of {@link AdxpHouseNumber }
     * 
     */
    public AdxpHouseNumber createAdxpHouseNumber() {
        return new AdxpHouseNumber();
    }

    /**
     * Create an instance of {@link IVLINT }
     * 
     */
    public IVLINT createIVLINT() {
        return new IVLINT();
    }

    /**
     * Create an instance of {@link IVXBPQ }
     * 
     */
    public IVXBPQ createIVXBPQ() {
        return new IVXBPQ();
    }

    /**
     * Create an instance of {@link EnGiven }
     * 
     */
    public EnGiven createEnGiven() {
        return new EnGiven();
    }

    /**
     * Create an instance of {@link IVXBMO }
     * 
     */
    public IVXBMO createIVXBMO() {
        return new IVXBMO();
    }

    /**
     * Create an instance of {@link REDSMT010001UVServiceDeliveryLocation }
     * 
     */
    public REDSMT010001UVServiceDeliveryLocation createREDSMT010001UVServiceDeliveryLocation() {
        return new REDSMT010001UVServiceDeliveryLocation();
    }

    /**
     * Create an instance of {@link PIVLTS }
     * 
     */
    public PIVLTS createPIVLTS() {
        return new PIVLTS();
    }

    /**
     * Create an instance of {@link ENXP }
     * 
     */
    public ENXP createENXP() {
        return new ENXP();
    }

    /**
     * Create an instance of {@link REDSMT010001UVLocation }
     * 
     */
    public REDSMT010001UVLocation createREDSMT010001UVLocation() {
        return new REDSMT010001UVLocation();
    }

    /**
     * Create an instance of {@link REDSMT010001UVSubject }
     * 
     */
    public REDSMT010001UVSubject createREDSMT010001UVSubject() {
        return new REDSMT010001UVSubject();
    }

    /**
     * Create an instance of {@link AdxpDeliveryModeIdentifier }
     * 
     */
    public AdxpDeliveryModeIdentifier createAdxpDeliveryModeIdentifier() {
        return new AdxpDeliveryModeIdentifier();
    }

    /**
     * Create an instance of {@link REDSMT010001UVSubject6 }
     * 
     */
    public REDSMT010001UVSubject6 createREDSMT010001UVSubject6() {
        return new REDSMT010001UVSubject6();
    }

    /**
     * Create an instance of {@link AdxpStreetName }
     * 
     */
    public AdxpStreetName createAdxpStreetName() {
        return new AdxpStreetName();
    }

    /**
     * Create an instance of {@link AdxpStreetNameType }
     * 
     */
    public AdxpStreetNameType createAdxpStreetNameType() {
        return new AdxpStreetNameType();
    }

    /**
     * Create an instance of {@link REDSMT010001UVSubject3 }
     * 
     */
    public REDSMT010001UVSubject3 createREDSMT010001UVSubject3() {
        return new REDSMT010001UVSubject3();
    }

    /**
     * Create an instance of {@link REDSMT010001UVSubject4 }
     * 
     */
    public REDSMT010001UVSubject4 createREDSMT010001UVSubject4() {
        return new REDSMT010001UVSubject4();
    }

    /**
     * Create an instance of {@link REDSMT010001UVSubject1 }
     * 
     */
    public REDSMT010001UVSubject1 createREDSMT010001UVSubject1() {
        return new REDSMT010001UVSubject1();
    }

    /**
     * Create an instance of {@link REDSMT010001UVSubject2 }
     * 
     */
    public REDSMT010001UVSubject2 createREDSMT010001UVSubject2() {
        return new REDSMT010001UVSubject2();
    }

    /**
     * Create an instance of {@link AdxpDirection }
     * 
     */
    public AdxpDirection createAdxpDirection() {
        return new AdxpDirection();
    }

    /**
     * Create an instance of {@link PPDTS }
     * 
     */
    public PPDTS createPPDTS() {
        return new PPDTS();
    }

    /**
     * Create an instance of {@link IVXBINT }
     * 
     */
    public IVXBINT createIVXBINT() {
        return new IVXBINT();
    }

    /**
     * Create an instance of {@link AdxpPostalCode }
     * 
     */
    public AdxpPostalCode createAdxpPostalCode() {
        return new AdxpPostalCode();
    }

    /**
     * Create an instance of {@link SXCMREAL }
     * 
     */
    public SXCMREAL createSXCMREAL() {
        return new SXCMREAL();
    }

    /**
     * Create an instance of {@link REDSMT010001UVAgeGroup }
     * 
     */
    public REDSMT010001UVAgeGroup createREDSMT010001UVAgeGroup() {
        return new REDSMT010001UVAgeGroup();
    }

    /**
     * Create an instance of {@link GLISTTS }
     * 
     */
    public GLISTTS createGLISTTS() {
        return new GLISTTS();
    }

    /**
     * Create an instance of {@link PQR }
     * 
     */
    public PQR createPQR() {
        return new PQR();
    }

    /**
     * Create an instance of {@link EIVLEvent }
     * 
     */
    public EIVLEvent createEIVLEvent() {
        return new EIVLEvent();
    }

    /**
     * Create an instance of {@link REDSMT010001UVAssignedEntity }
     * 
     */
    public REDSMT010001UVAssignedEntity createREDSMT010001UVAssignedEntity() {
        return new REDSMT010001UVAssignedEntity();
    }

    /**
     * Create an instance of {@link AdxpStreetNameBase }
     * 
     */
    public AdxpStreetNameBase createAdxpStreetNameBase() {
        return new AdxpStreetNameBase();
    }

    /**
     * Create an instance of {@link Thumbnail }
     * 
     */
    public Thumbnail createThumbnail() {
        return new Thumbnail();
    }

    /**
     * Create an instance of {@link AdxpAdditionalLocator }
     * 
     */
    public AdxpAdditionalLocator createAdxpAdditionalLocator() {
        return new AdxpAdditionalLocator();
    }

    /**
     * Create an instance of {@link REDSMT010001UVOrganization }
     * 
     */
    public REDSMT010001UVOrganization createREDSMT010001UVOrganization() {
        return new REDSMT010001UVOrganization();
    }

    /**
     * Create an instance of {@link RTO }
     * 
     */
    public RTO createRTO() {
        return new RTO();
    }

    /**
     * Create an instance of {@link GLISTPQ }
     * 
     */
    public GLISTPQ createGLISTPQ() {
        return new GLISTPQ();
    }

    /**
     * Create an instance of {@link REDSMT010001UVSeverityObservation }
     * 
     */
    public REDSMT010001UVSeverityObservation createREDSMT010001UVSeverityObservation() {
        return new REDSMT010001UVSeverityObservation();
    }

    /**
     * Create an instance of {@link EnFamily }
     * 
     */
    public EnFamily createEnFamily() {
        return new EnFamily();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVMainSearchCriteria }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "mainSearchCriteria")
    public JAXBElement<REDSMT010001UVMainSearchCriteria> createMainSearchCriteria(REDSMT010001UVMainSearchCriteria value) {
        return new JAXBElement<REDSMT010001UVMainSearchCriteria>(_MainSearchCriteria_QNAME, REDSMT010001UVMainSearchCriteria.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVEncounter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "encounter")
    public JAXBElement<REDSMT010001UVEncounter> createEncounter(REDSMT010001UVEncounter value) {
        return new JAXBElement<REDSMT010001UVEncounter>(_Encounter_QNAME, REDSMT010001UVEncounter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVInformationRecipient }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "informationRecipient")
    public JAXBElement<REDSMT010001UVInformationRecipient> createInformationRecipient(REDSMT010001UVInformationRecipient value) {
        return new JAXBElement<REDSMT010001UVInformationRecipient>(_InformationRecipient_QNAME, REDSMT010001UVInformationRecipient.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVSubTopic }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "subTopic")
    public JAXBElement<REDSMT010001UVSubTopic> createSubTopic(REDSMT010001UVSubTopic value) {
        return new JAXBElement<REDSMT010001UVSubTopic>(_SubTopic_QNAME, REDSMT010001UVSubTopic.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVPerformer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "performer")
    public JAXBElement<REDSMT010001UVPerformer> createPerformer(REDSMT010001UVPerformer value) {
        return new JAXBElement<REDSMT010001UVPerformer>(_Performer_QNAME, REDSMT010001UVPerformer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVKnowledgeRequestNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "REDS_MT010001UV.KnowledgeRequestNotification")
    public JAXBElement<REDSMT010001UVKnowledgeRequestNotification> createREDSMT010001UVKnowledgeRequestNotification(REDSMT010001UVKnowledgeRequestNotification value) {
        return new JAXBElement<REDSMT010001UVKnowledgeRequestNotification>(_REDSMT010001UVKnowledgeRequestNotification_QNAME, REDSMT010001UVKnowledgeRequestNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVTaskContext }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "taskContext")
    public JAXBElement<REDSMT010001UVTaskContext> createTaskContext(REDSMT010001UVTaskContext value) {
        return new JAXBElement<REDSMT010001UVTaskContext>(_TaskContext_QNAME, REDSMT010001UVTaskContext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVPatientContext }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "patientContext")
    public JAXBElement<REDSMT010001UVPatientContext> createPatientContext(REDSMT010001UVPatientContext value) {
        return new JAXBElement<REDSMT010001UVPatientContext>(_PatientContext_QNAME, REDSMT010001UVPatientContext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVAgeGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "ageGroup", scope = REDSMT010001UVSubject6 .class)
    public JAXBElement<REDSMT010001UVAgeGroup> createREDSMT010001UVSubject6AgeGroup(REDSMT010001UVAgeGroup value) {
        return new JAXBElement<REDSMT010001UVAgeGroup>(_REDSMT010001UVSubject6AgeGroup_QNAME, REDSMT010001UVAgeGroup.class, REDSMT010001UVSubject6 .class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVAge }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "age", scope = REDSMT010001UVSubject6 .class)
    public JAXBElement<REDSMT010001UVAge> createREDSMT010001UVSubject6Age(REDSMT010001UVAge value) {
        return new JAXBElement<REDSMT010001UVAge>(_REDSMT010001UVSubject6Age_QNAME, REDSMT010001UVAge.class, REDSMT010001UVSubject6 .class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVLocation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "location", scope = REDSMT010001UVEncounter.class)
    public JAXBElement<REDSMT010001UVLocation> createREDSMT010001UVEncounterLocation(REDSMT010001UVLocation value) {
        return new JAXBElement<REDSMT010001UVLocation>(_REDSMT010001UVEncounterLocation_QNAME, REDSMT010001UVLocation.class, REDSMT010001UVEncounter.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnSuffix }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "suffix", scope = EN.class)
    public JAXBElement<EnSuffix> createENSuffix(EnSuffix value) {
        return new JAXBElement<EnSuffix>(_ENSuffix_QNAME, EnSuffix.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnDelimiter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "delimiter", scope = EN.class)
    public JAXBElement<EnDelimiter> createENDelimiter(EnDelimiter value) {
        return new JAXBElement<EnDelimiter>(_ENDelimiter_QNAME, EnDelimiter.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "validTime", scope = EN.class)
    public JAXBElement<IVLTS> createENValidTime(IVLTS value) {
        return new JAXBElement<IVLTS>(_ENValidTime_QNAME, IVLTS.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnPrefix }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "prefix", scope = EN.class)
    public JAXBElement<EnPrefix> createENPrefix(EnPrefix value) {
        return new JAXBElement<EnPrefix>(_ENPrefix_QNAME, EnPrefix.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnFamily }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "family", scope = EN.class)
    public JAXBElement<EnFamily> createENFamily(EnFamily value) {
        return new JAXBElement<EnFamily>(_ENFamily_QNAME, EnFamily.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnGiven }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "given", scope = EN.class)
    public JAXBElement<EnGiven> createENGiven(EnGiven value) {
        return new JAXBElement<EnGiven>(_ENGiven_QNAME, EnGiven.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLTS.class)
    public JAXBElement<IVXBTS> createIVLTSHigh(IVXBTS value) {
        return new JAXBElement<IVXBTS>(_IVLTSHigh_QNAME, IVXBTS.class, IVLTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLTS.class)
    public JAXBElement<IVXBTS> createIVLTSLow(IVXBTS value) {
        return new JAXBElement<IVXBTS>(_IVLTSLow_QNAME, IVXBTS.class, IVLTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLTS.class)
    public JAXBElement<TS> createIVLTSCenter(TS value) {
        return new JAXBElement<TS>(_IVLTSCenter_QNAME, TS.class, IVLTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLTS.class)
    public JAXBElement<PQ> createIVLTSWidth(PQ value) {
        return new JAXBElement<PQ>(_IVLTSWidth_QNAME, PQ.class, IVLTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVPatient }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "patient", scope = REDSMT010001UVInformationRecipient.class)
    public JAXBElement<REDSMT010001UVPatient> createREDSMT010001UVInformationRecipientPatient(REDSMT010001UVPatient value) {
        return new JAXBElement<REDSMT010001UVPatient>(_REDSMT010001UVInformationRecipientPatient_QNAME, REDSMT010001UVPatient.class, REDSMT010001UVInformationRecipient.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVHealthCareProvider }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "healthCareProvider", scope = REDSMT010001UVInformationRecipient.class)
    public JAXBElement<REDSMT010001UVHealthCareProvider> createREDSMT010001UVInformationRecipientHealthCareProvider(REDSMT010001UVHealthCareProvider value) {
        return new JAXBElement<REDSMT010001UVHealthCareProvider>(_REDSMT010001UVInformationRecipientHealthCareProvider_QNAME, REDSMT010001UVHealthCareProvider.class, REDSMT010001UVInformationRecipient.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBREAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLREAL.class)
    public JAXBElement<IVXBREAL> createIVLREALHigh(IVXBREAL value) {
        return new JAXBElement<IVXBREAL>(_IVLTSHigh_QNAME, IVXBREAL.class, IVLREAL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBREAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLREAL.class)
    public JAXBElement<IVXBREAL> createIVLREALLow(IVXBREAL value) {
        return new JAXBElement<IVXBREAL>(_IVLTSLow_QNAME, IVXBREAL.class, IVLREAL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLREAL.class)
    public JAXBElement<REAL> createIVLREALCenter(REAL value) {
        return new JAXBElement<REAL>(_IVLTSCenter_QNAME, REAL.class, IVLREAL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLREAL.class)
    public JAXBElement<REAL> createIVLREALWidth(REAL value) {
        return new JAXBElement<REAL>(_IVLTSWidth_QNAME, REAL.class, IVLREAL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBINT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLINT.class)
    public JAXBElement<IVXBINT> createIVLINTHigh(IVXBINT value) {
        return new JAXBElement<IVXBINT>(_IVLTSHigh_QNAME, IVXBINT.class, IVLINT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBINT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLINT.class)
    public JAXBElement<IVXBINT> createIVLINTLow(IVXBINT value) {
        return new JAXBElement<IVXBINT>(_IVLTSLow_QNAME, IVXBINT.class, IVLINT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link INT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLINT.class)
    public JAXBElement<INT> createIVLINTCenter(INT value) {
        return new JAXBElement<INT>(_IVLTSCenter_QNAME, INT.class, IVLINT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link INT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLINT.class)
    public JAXBElement<INT> createIVLINTWidth(INT value) {
        return new JAXBElement<INT>(_IVLTSWidth_QNAME, INT.class, IVLINT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVPerson }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "healthCarePerson", scope = REDSMT010001UVHealthCareProvider.class)
    public JAXBElement<REDSMT010001UVPerson> createREDSMT010001UVHealthCareProviderHealthCarePerson(REDSMT010001UVPerson value) {
        return new JAXBElement<REDSMT010001UVPerson>(_REDSMT010001UVHealthCareProviderHealthCarePerson_QNAME, REDSMT010001UVPerson.class, REDSMT010001UVHealthCareProvider.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBMO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLMO.class)
    public JAXBElement<IVXBMO> createIVLMOHigh(IVXBMO value) {
        return new JAXBElement<IVXBMO>(_IVLTSHigh_QNAME, IVXBMO.class, IVLMO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBMO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLMO.class)
    public JAXBElement<IVXBMO> createIVLMOLow(IVXBMO value) {
        return new JAXBElement<IVXBMO>(_IVLTSLow_QNAME, IVXBMO.class, IVLMO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLMO.class)
    public JAXBElement<MO> createIVLMOCenter(MO value) {
        return new JAXBElement<MO>(_IVLTSCenter_QNAME, MO.class, IVLMO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLMO.class)
    public JAXBElement<MO> createIVLMOWidth(MO value) {
        return new JAXBElement<MO>(_IVLTSWidth_QNAME, MO.class, IVLMO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVPatient }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "patient", scope = REDSMT010001UVPerformer.class)
    public JAXBElement<REDSMT010001UVPatient> createREDSMT010001UVPerformerPatient(REDSMT010001UVPatient value) {
        return new JAXBElement<REDSMT010001UVPatient>(_REDSMT010001UVInformationRecipientPatient_QNAME, REDSMT010001UVPatient.class, REDSMT010001UVPerformer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVHealthCareProvider }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "healthCareProvider", scope = REDSMT010001UVPerformer.class)
    public JAXBElement<REDSMT010001UVHealthCareProvider> createREDSMT010001UVPerformerHealthCareProvider(REDSMT010001UVHealthCareProvider value) {
        return new JAXBElement<REDSMT010001UVHealthCareProvider>(_REDSMT010001UVInformationRecipientHealthCareProvider_QNAME, REDSMT010001UVHealthCareProvider.class, REDSMT010001UVPerformer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVOrganization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "representedOrganization", scope = REDSMT010001UVAssignedEntity.class)
    public JAXBElement<REDSMT010001UVOrganization> createREDSMT010001UVAssignedEntityRepresentedOrganization(REDSMT010001UVOrganization value) {
        return new JAXBElement<REDSMT010001UVOrganization>(_REDSMT010001UVAssignedEntityRepresentedOrganization_QNAME, REDSMT010001UVOrganization.class, REDSMT010001UVAssignedEntity.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVAuthorizedPerson }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "assignedAuthorizedPerson", scope = REDSMT010001UVAssignedEntity.class)
    public JAXBElement<REDSMT010001UVAuthorizedPerson> createREDSMT010001UVAssignedEntityAssignedAuthorizedPerson(REDSMT010001UVAuthorizedPerson value) {
        return new JAXBElement<REDSMT010001UVAuthorizedPerson>(_REDSMT010001UVAssignedEntityAssignedAuthorizedPerson_QNAME, REDSMT010001UVAuthorizedPerson.class, REDSMT010001UVAssignedEntity.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVPerson }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "patientPerson", scope = REDSMT010001UVPatient.class)
    public JAXBElement<REDSMT010001UVPerson> createREDSMT010001UVPatientPatientPerson(REDSMT010001UVPerson value) {
        return new JAXBElement<REDSMT010001UVPerson>(_REDSMT010001UVPatientPatientPerson_QNAME, REDSMT010001UVPerson.class, REDSMT010001UVPatient.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVInformationRecipient }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "informationRecipient", scope = REDSMT010001UVKnowledgeRequestNotification.class)
    public JAXBElement<REDSMT010001UVInformationRecipient> createREDSMT010001UVKnowledgeRequestNotificationInformationRecipient(REDSMT010001UVInformationRecipient value) {
        return new JAXBElement<REDSMT010001UVInformationRecipient>(_InformationRecipient_QNAME, REDSMT010001UVInformationRecipient.class, REDSMT010001UVKnowledgeRequestNotification.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVPerformer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "performer", scope = REDSMT010001UVKnowledgeRequestNotification.class)
    public JAXBElement<REDSMT010001UVPerformer> createREDSMT010001UVKnowledgeRequestNotificationPerformer(REDSMT010001UVPerformer value) {
        return new JAXBElement<REDSMT010001UVPerformer>(_Performer_QNAME, REDSMT010001UVPerformer.class, REDSMT010001UVKnowledgeRequestNotification.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVSubject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "subject1", scope = REDSMT010001UVKnowledgeRequestNotification.class)
    public JAXBElement<REDSMT010001UVSubject> createREDSMT010001UVKnowledgeRequestNotificationSubject1(REDSMT010001UVSubject value) {
        return new JAXBElement<REDSMT010001UVSubject>(_REDSMT010001UVKnowledgeRequestNotificationSubject1_QNAME, REDSMT010001UVSubject.class, REDSMT010001UVKnowledgeRequestNotification.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVHolder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "holder", scope = REDSMT010001UVKnowledgeRequestNotification.class)
    public JAXBElement<REDSMT010001UVHolder> createREDSMT010001UVKnowledgeRequestNotificationHolder(REDSMT010001UVHolder value) {
        return new JAXBElement<REDSMT010001UVHolder>(_REDSMT010001UVKnowledgeRequestNotificationHolder_QNAME, REDSMT010001UVHolder.class, REDSMT010001UVKnowledgeRequestNotification.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVSubject2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "subject3", scope = REDSMT010001UVKnowledgeRequestNotification.class)
    public JAXBElement<REDSMT010001UVSubject2> createREDSMT010001UVKnowledgeRequestNotificationSubject3(REDSMT010001UVSubject2 value) {
        return new JAXBElement<REDSMT010001UVSubject2>(_REDSMT010001UVKnowledgeRequestNotificationSubject3_QNAME, REDSMT010001UVSubject2 .class, REDSMT010001UVKnowledgeRequestNotification.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVSubject1 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "subject2", scope = REDSMT010001UVKnowledgeRequestNotification.class)
    public JAXBElement<REDSMT010001UVSubject1> createREDSMT010001UVKnowledgeRequestNotificationSubject2(REDSMT010001UVSubject1 value) {
        return new JAXBElement<REDSMT010001UVSubject1>(_REDSMT010001UVKnowledgeRequestNotificationSubject2_QNAME, REDSMT010001UVSubject1 .class, REDSMT010001UVKnowledgeRequestNotification.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVComponent1 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "componentOf", scope = REDSMT010001UVKnowledgeRequestNotification.class)
    public JAXBElement<REDSMT010001UVComponent1> createREDSMT010001UVKnowledgeRequestNotificationComponentOf(REDSMT010001UVComponent1 value) {
        return new JAXBElement<REDSMT010001UVComponent1>(_REDSMT010001UVKnowledgeRequestNotificationComponentOf_QNAME, REDSMT010001UVComponent1 .class, REDSMT010001UVKnowledgeRequestNotification.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLPQ.class)
    public JAXBElement<IVXBPQ> createIVLPQHigh(IVXBPQ value) {
        return new JAXBElement<IVXBPQ>(_IVLTSHigh_QNAME, IVXBPQ.class, IVLPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLPQ.class)
    public JAXBElement<IVXBPQ> createIVLPQLow(IVXBPQ value) {
        return new JAXBElement<IVXBPQ>(_IVLTSLow_QNAME, IVXBPQ.class, IVLPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLPQ.class)
    public JAXBElement<PQ> createIVLPQCenter(PQ value) {
        return new JAXBElement<PQ>(_IVLTSCenter_QNAME, PQ.class, IVLPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLPQ.class)
    public JAXBElement<PQ> createIVLPQWidth(PQ value) {
        return new JAXBElement<PQ>(_IVLTSWidth_QNAME, PQ.class, IVLPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBPPDPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLPPDPQ.class)
    public JAXBElement<IVXBPPDPQ> createIVLPPDPQHigh(IVXBPPDPQ value) {
        return new JAXBElement<IVXBPPDPQ>(_IVLTSHigh_QNAME, IVXBPPDPQ.class, IVLPPDPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBPPDPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLPPDPQ.class)
    public JAXBElement<IVXBPPDPQ> createIVLPPDPQLow(IVXBPPDPQ value) {
        return new JAXBElement<IVXBPPDPQ>(_IVLTSLow_QNAME, IVXBPPDPQ.class, IVLPPDPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PPDPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLPPDPQ.class)
    public JAXBElement<PPDPQ> createIVLPPDPQCenter(PPDPQ value) {
        return new JAXBElement<PPDPQ>(_IVLTSCenter_QNAME, PPDPQ.class, IVLPPDPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PPDPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLPPDPQ.class)
    public JAXBElement<PPDPQ> createIVLPPDPQWidth(PPDPQ value) {
        return new JAXBElement<PPDPQ>(_IVLTSWidth_QNAME, PPDPQ.class, IVLPPDPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDeliveryModeIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "deliveryModeIdentifier", scope = AD.class)
    public JAXBElement<AdxpDeliveryModeIdentifier> createADDeliveryModeIdentifier(AdxpDeliveryModeIdentifier value) {
        return new JAXBElement<AdxpDeliveryModeIdentifier>(_ADDeliveryModeIdentifier_QNAME, AdxpDeliveryModeIdentifier.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpHouseNumber }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "houseNumber", scope = AD.class)
    public JAXBElement<AdxpHouseNumber> createADHouseNumber(AdxpHouseNumber value) {
        return new JAXBElement<AdxpHouseNumber>(_ADHouseNumber_QNAME, AdxpHouseNumber.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "state", scope = AD.class)
    public JAXBElement<AdxpState> createADState(AdxpState value) {
        return new JAXBElement<AdxpState>(_ADState_QNAME, AdxpState.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpCity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "city", scope = AD.class)
    public JAXBElement<AdxpCity> createADCity(AdxpCity value) {
        return new JAXBElement<AdxpCity>(_ADCity_QNAME, AdxpCity.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpAdditionalLocator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "additionalLocator", scope = AD.class)
    public JAXBElement<AdxpAdditionalLocator> createADAdditionalLocator(AdxpAdditionalLocator value) {
        return new JAXBElement<AdxpAdditionalLocator>(_ADAdditionalLocator_QNAME, AdxpAdditionalLocator.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpStreetAddressLine }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "streetAddressLine", scope = AD.class)
    public JAXBElement<AdxpStreetAddressLine> createADStreetAddressLine(AdxpStreetAddressLine value) {
        return new JAXBElement<AdxpStreetAddressLine>(_ADStreetAddressLine_QNAME, AdxpStreetAddressLine.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDeliveryInstallationArea }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "deliveryInstallationArea", scope = AD.class)
    public JAXBElement<AdxpDeliveryInstallationArea> createADDeliveryInstallationArea(AdxpDeliveryInstallationArea value) {
        return new JAXBElement<AdxpDeliveryInstallationArea>(_ADDeliveryInstallationArea_QNAME, AdxpDeliveryInstallationArea.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpStreetNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "streetNameType", scope = AD.class)
    public JAXBElement<AdxpStreetNameType> createADStreetNameType(AdxpStreetNameType value) {
        return new JAXBElement<AdxpStreetNameType>(_ADStreetNameType_QNAME, AdxpStreetNameType.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDeliveryInstallationQualifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "deliveryInstallationQualifier", scope = AD.class)
    public JAXBElement<AdxpDeliveryInstallationQualifier> createADDeliveryInstallationQualifier(AdxpDeliveryInstallationQualifier value) {
        return new JAXBElement<AdxpDeliveryInstallationQualifier>(_ADDeliveryInstallationQualifier_QNAME, AdxpDeliveryInstallationQualifier.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDirection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "direction", scope = AD.class)
    public JAXBElement<AdxpDirection> createADDirection(AdxpDirection value) {
        return new JAXBElement<AdxpDirection>(_ADDirection_QNAME, AdxpDirection.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpCensusTract }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "censusTract", scope = AD.class)
    public JAXBElement<AdxpCensusTract> createADCensusTract(AdxpCensusTract value) {
        return new JAXBElement<AdxpCensusTract>(_ADCensusTract_QNAME, AdxpCensusTract.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpUnitID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "unitID", scope = AD.class)
    public JAXBElement<AdxpUnitID> createADUnitID(AdxpUnitID value) {
        return new JAXBElement<AdxpUnitID>(_ADUnitID_QNAME, AdxpUnitID.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpPostalCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "postalCode", scope = AD.class)
    public JAXBElement<AdxpPostalCode> createADPostalCode(AdxpPostalCode value) {
        return new JAXBElement<AdxpPostalCode>(_ADPostalCode_QNAME, AdxpPostalCode.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpStreetName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "streetName", scope = AD.class)
    public JAXBElement<AdxpStreetName> createADStreetName(AdxpStreetName value) {
        return new JAXBElement<AdxpStreetName>(_ADStreetName_QNAME, AdxpStreetName.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDeliveryInstallationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "deliveryInstallationType", scope = AD.class)
    public JAXBElement<AdxpDeliveryInstallationType> createADDeliveryInstallationType(AdxpDeliveryInstallationType value) {
        return new JAXBElement<AdxpDeliveryInstallationType>(_ADDeliveryInstallationType_QNAME, AdxpDeliveryInstallationType.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpStreetNameBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "streetNameBase", scope = AD.class)
    public JAXBElement<AdxpStreetNameBase> createADStreetNameBase(AdxpStreetNameBase value) {
        return new JAXBElement<AdxpStreetNameBase>(_ADStreetNameBase_QNAME, AdxpStreetNameBase.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDeliveryMode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "deliveryMode", scope = AD.class)
    public JAXBElement<AdxpDeliveryMode> createADDeliveryMode(AdxpDeliveryMode value) {
        return new JAXBElement<AdxpDeliveryMode>(_ADDeliveryMode_QNAME, AdxpDeliveryMode.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpPostBox }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "postBox", scope = AD.class)
    public JAXBElement<AdxpPostBox> createADPostBox(AdxpPostBox value) {
        return new JAXBElement<AdxpPostBox>(_ADPostBox_QNAME, AdxpPostBox.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpCountry }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "country", scope = AD.class)
    public JAXBElement<AdxpCountry> createADCountry(AdxpCountry value) {
        return new JAXBElement<AdxpCountry>(_ADCountry_QNAME, AdxpCountry.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDeliveryAddressLine }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "deliveryAddressLine", scope = AD.class)
    public JAXBElement<AdxpDeliveryAddressLine> createADDeliveryAddressLine(AdxpDeliveryAddressLine value) {
        return new JAXBElement<AdxpDeliveryAddressLine>(_ADDeliveryAddressLine_QNAME, AdxpDeliveryAddressLine.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SXCMTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "useablePeriod", scope = AD.class)
    public JAXBElement<SXCMTS> createADUseablePeriod(SXCMTS value) {
        return new JAXBElement<SXCMTS>(_ADUseablePeriod_QNAME, SXCMTS.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpCareOf }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "careOf", scope = AD.class)
    public JAXBElement<AdxpCareOf> createADCareOf(AdxpCareOf value) {
        return new JAXBElement<AdxpCareOf>(_ADCareOf_QNAME, AdxpCareOf.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpUnitType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "unitType", scope = AD.class)
    public JAXBElement<AdxpUnitType> createADUnitType(AdxpUnitType value) {
        return new JAXBElement<AdxpUnitType>(_ADUnitType_QNAME, AdxpUnitType.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpPrecinct }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "precinct", scope = AD.class)
    public JAXBElement<AdxpPrecinct> createADPrecinct(AdxpPrecinct value) {
        return new JAXBElement<AdxpPrecinct>(_ADPrecinct_QNAME, AdxpPrecinct.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDelimiter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "delimiter", scope = AD.class)
    public JAXBElement<AdxpDelimiter> createADDelimiter(AdxpDelimiter value) {
        return new JAXBElement<AdxpDelimiter>(_ENDelimiter_QNAME, AdxpDelimiter.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpBuildingNumberSuffix }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "buildingNumberSuffix", scope = AD.class)
    public JAXBElement<AdxpBuildingNumberSuffix> createADBuildingNumberSuffix(AdxpBuildingNumberSuffix value) {
        return new JAXBElement<AdxpBuildingNumberSuffix>(_ADBuildingNumberSuffix_QNAME, AdxpBuildingNumberSuffix.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpHouseNumberNumeric }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "houseNumberNumeric", scope = AD.class)
    public JAXBElement<AdxpHouseNumberNumeric> createADHouseNumberNumeric(AdxpHouseNumberNumeric value) {
        return new JAXBElement<AdxpHouseNumberNumeric>(_ADHouseNumberNumeric_QNAME, AdxpHouseNumberNumeric.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpCounty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "county", scope = AD.class)
    public JAXBElement<AdxpCounty> createADCounty(AdxpCounty value) {
        return new JAXBElement<AdxpCounty>(_ADCounty_QNAME, AdxpCounty.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBPPDTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLPPDTS.class)
    public JAXBElement<IVXBPPDTS> createIVLPPDTSHigh(IVXBPPDTS value) {
        return new JAXBElement<IVXBPPDTS>(_IVLTSHigh_QNAME, IVXBPPDTS.class, IVLPPDTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBPPDTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLPPDTS.class)
    public JAXBElement<IVXBPPDTS> createIVLPPDTSLow(IVXBPPDTS value) {
        return new JAXBElement<IVXBPPDTS>(_IVLTSLow_QNAME, IVXBPPDTS.class, IVLPPDTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PPDTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLPPDTS.class)
    public JAXBElement<PPDTS> createIVLPPDTSCenter(PPDTS value) {
        return new JAXBElement<PPDTS>(_IVLTSCenter_QNAME, PPDTS.class, IVLPPDTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PPDPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLPPDTS.class)
    public JAXBElement<PPDPQ> createIVLPPDTSWidth(PPDPQ value) {
        return new JAXBElement<PPDPQ>(_IVLTSWidth_QNAME, PPDPQ.class, IVLPPDTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVSubject4 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "subject", scope = REDSMT010001UVMainSearchCriteria.class)
    public JAXBElement<REDSMT010001UVSubject4> createREDSMT010001UVMainSearchCriteriaSubject(REDSMT010001UVSubject4 value) {
        return new JAXBElement<REDSMT010001UVSubject4>(_REDSMT010001UVMainSearchCriteriaSubject_QNAME, REDSMT010001UVSubject4 .class, REDSMT010001UVMainSearchCriteria.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REDSMT010001UVPatientPerson }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "patientPerson", scope = REDSMT010001UVPatientContext.class)
    public JAXBElement<REDSMT010001UVPatientPerson> createREDSMT010001UVPatientContextPatientPerson(REDSMT010001UVPatientPerson value) {
        return new JAXBElement<REDSMT010001UVPatientPerson>(_REDSMT010001UVPatientPatientPerson_QNAME, REDSMT010001UVPatientPerson.class, REDSMT010001UVPatientContext.class, value);
    }

}
