//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.30 at 11:18:11 PM EST 
//


package com.glenwood.glaceemr.infobutton.utils.KnowledgeRequest;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for REDS_MT010001UV.KnowledgeRequestNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REDS_MT010001UV.KnowledgeRequestNotification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;element name="id" type="{urn:hl7-org:v3}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="effectiveTime" type="{urn:hl7-org:v3}TS" minOccurs="0"/>
 *         &lt;element name="subject1" type="{urn:hl7-org:v3}REDS_MT010001UV.Subject" minOccurs="0"/>
 *         &lt;element name="holder" type="{urn:hl7-org:v3}REDS_MT010001UV.Holder" minOccurs="0"/>
 *         &lt;element name="performer" type="{urn:hl7-org:v3}REDS_MT010001UV.Performer" minOccurs="0"/>
 *         &lt;element name="informationRecipient" type="{urn:hl7-org:v3}REDS_MT010001UV.InformationRecipient" minOccurs="0"/>
 *         &lt;element name="subject2" type="{urn:hl7-org:v3}REDS_MT010001UV.Subject1" minOccurs="0"/>
 *         &lt;element name="subject3" type="{urn:hl7-org:v3}REDS_MT010001UV.Subject2" minOccurs="0"/>
 *         &lt;element name="subject4" type="{urn:hl7-org:v3}REDS_MT010001UV.Subject3" maxOccurs="unbounded"/>
 *         &lt;element name="componentOf" type="{urn:hl7-org:v3}REDS_MT010001UV.Component1" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *       &lt;attribute name="classCode" use="required" type="{urn:hl7-org:v3}ActClassRoot" />
 *       &lt;attribute name="moodCode" use="required" type="{urn:hl7-org:v3}cs" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REDS_MT010001UV.KnowledgeRequestNotification", propOrder = {
    "realmCode",
    "typeId",
    "templateId",
    "id",
    "effectiveTime",
    "subject1",
    "holder",
    "performer",
    "informationRecipient",
    "subject2",
    "subject3",
    "subject4",
    "componentOf"
})
public class REDSMT010001UVKnowledgeRequestNotification {

    protected List<CS> realmCode;
    protected II typeId;
    protected List<II> templateId;
    protected List<II> id;
    protected TS effectiveTime;
    @XmlElementRef(name = "subject1", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<REDSMT010001UVSubject> subject1;
    @XmlElementRef(name = "holder", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<REDSMT010001UVHolder> holder;
    @XmlElementRef(name = "performer", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<REDSMT010001UVPerformer> performer;
    @XmlElementRef(name = "informationRecipient", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<REDSMT010001UVInformationRecipient> informationRecipient;
    @XmlElementRef(name = "subject2", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<REDSMT010001UVSubject1> subject2;
    @XmlElementRef(name = "subject3", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<REDSMT010001UVSubject2> subject3;
    @XmlElement(required = true, nillable = true)
    protected List<REDSMT010001UVSubject3> subject4;
    @XmlElementRef(name = "componentOf", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<REDSMT010001UVComponent1> componentOf;
    @XmlAttribute(name = "classCode", required = true)
    protected ActClassRoot classCode;
    @XmlAttribute(name = "moodCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String moodCode;

    /**
     * Gets the value of the realmCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     * 
     * 
     */
    public List<CS> getRealmCode() {
        if (realmCode == null) {
            realmCode = new ArrayList<CS>();
        }
        return this.realmCode;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setTypeId(II value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getTemplateId() {
        if (templateId == null) {
            templateId = new ArrayList<II>();
        }
        return this.templateId;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getId() {
        if (id == null) {
            id = new ArrayList<II>();
        }
        return this.id;
    }

    /**
     * Gets the value of the effectiveTime property.
     * 
     * @return
     *     possible object is
     *     {@link TS }
     *     
     */
    public TS getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * Sets the value of the effectiveTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TS }
     *     
     */
    public void setEffectiveTime(TS value) {
        this.effectiveTime = value;
    }

    /**
     * Gets the value of the subject1 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVSubject }{@code >}
     *     
     */
    public JAXBElement<REDSMT010001UVSubject> getSubject1() {
        return subject1;
    }

    /**
     * Sets the value of the subject1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVSubject }{@code >}
     *     
     */
    public void setSubject1(JAXBElement<REDSMT010001UVSubject> value) {
        this.subject1 = value;
    }

    /**
     * Gets the value of the holder property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVHolder }{@code >}
     *     
     */
    public JAXBElement<REDSMT010001UVHolder> getHolder() {
        return holder;
    }

    /**
     * Sets the value of the holder property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVHolder }{@code >}
     *     
     */
    public void setHolder(JAXBElement<REDSMT010001UVHolder> value) {
        this.holder = value;
    }

    /**
     * Gets the value of the performer property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVPerformer }{@code >}
     *     
     */
    public JAXBElement<REDSMT010001UVPerformer> getPerformer() {
        return performer;
    }

    /**
     * Sets the value of the performer property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVPerformer }{@code >}
     *     
     */
    public void setPerformer(JAXBElement<REDSMT010001UVPerformer> value) {
        this.performer = value;
    }

    /**
     * Gets the value of the informationRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVInformationRecipient }{@code >}
     *     
     */
    public JAXBElement<REDSMT010001UVInformationRecipient> getInformationRecipient() {
        return informationRecipient;
    }

    /**
     * Sets the value of the informationRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVInformationRecipient }{@code >}
     *     
     */
    public void setInformationRecipient(JAXBElement<REDSMT010001UVInformationRecipient> value) {
        this.informationRecipient = value;
    }

    /**
     * Gets the value of the subject2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVSubject1 }{@code >}
     *     
     */
    public JAXBElement<REDSMT010001UVSubject1> getSubject2() {
        return subject2;
    }

    /**
     * Sets the value of the subject2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVSubject1 }{@code >}
     *     
     */
    public void setSubject2(JAXBElement<REDSMT010001UVSubject1> value) {
        this.subject2 = value;
    }

    /**
     * Gets the value of the subject3 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVSubject2 }{@code >}
     *     
     */
    public JAXBElement<REDSMT010001UVSubject2> getSubject3() {
        return subject3;
    }

    /**
     * Sets the value of the subject3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVSubject2 }{@code >}
     *     
     */
    public void setSubject3(JAXBElement<REDSMT010001UVSubject2> value) {
        this.subject3 = value;
    }

    /**
     * Gets the value of the subject4 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subject4 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubject4().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link REDSMT010001UVSubject3 }
     * 
     * 
     */
    public List<REDSMT010001UVSubject3> getSubject4() {
        if (subject4 == null) {
            subject4 = new ArrayList<REDSMT010001UVSubject3>();
        }
        return this.subject4;
    }

    /**
     * Gets the value of the componentOf property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVComponent1 }{@code >}
     *     
     */
    public JAXBElement<REDSMT010001UVComponent1> getComponentOf() {
        return componentOf;
    }

    /**
     * Sets the value of the componentOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVComponent1 }{@code >}
     *     
     */
    public void setComponentOf(JAXBElement<REDSMT010001UVComponent1> value) {
        this.componentOf = value;
    }

    /**
     * Gets the value of the classCode property.
     * 
     * @return
     *     possible object is
     *     {@link ActClassRoot }
     *     
     */
    public ActClassRoot getClassCode() {
        return classCode;
    }

    /**
     * Sets the value of the classCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActClassRoot }
     *     
     */
    public void setClassCode(ActClassRoot value) {
        this.classCode = value;
    }

    /**
     * Gets the value of the moodCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoodCode() {
        return moodCode;
    }

    /**
     * Sets the value of the moodCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoodCode(String value) {
        this.moodCode = value;
    }

}
