//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 01:29:32 PM EDT 
//


package com.glenwood.glaceemr.gateway.utils.message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.glenwood.glaceemr.gateway.utils.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GatewayMessage_QNAME = new QName("http://www.glenwood.com/hie/structure", "gateway_message");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.glenwood.glaceemr.gateway.utils.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GatewayMessage }
     * 
     */
    public GatewayMessage createGatewayMessage() {
        return new GatewayMessage();
    }

    /**
     * Create an instance of {@link To }
     * 
     */
    public To createTo() {
        return new To();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link From }
     * 
     */
    public From createFrom() {
        return new From();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GatewayMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.glenwood.com/hie/structure", name = "gateway_message")
    public JAXBElement<GatewayMessage> createGatewayMessage(GatewayMessage value) {
        return new JAXBElement<GatewayMessage>(_GatewayMessage_QNAME, GatewayMessage.class, null, value);
    }

}
