//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 01:29:32 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.glenwood.com/hie/structure", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.glenwood.glaceemr.gateway.utils.message;
